### ISSUE TITLE
pnpm dev 以及 getUserInfo mock接口有点小问题

### ISSUE THREAD

**Issue by MYxu** [zmtlwzy/zmtlwzy-admin#4]
本地node版本14.15.1

1、build/vite/plugin/msw.ts
replaceAll函数存在不兼容情况报错replaceAll is not a function，建议使用replace('/\\/g', '/')

2、getUserInfo接口里面的getRequestToken方法有问题，应该是req?.headers?.headers?.authorization才对，不应该是req?.headers?._headers?.authorization

**Comment by zmtlwzy** [comment]
1 . replaceAll 已替换为 replace。
2. 从vue-plugin-mock 替换为 msw 后已更换为 req?.headers?._headers?.authorization，尝试把依赖更新一下看看。

**Comment by MYxu** [comment]
第二问题我的意思是，axios发起请求时，token是放在req.headers.headers.authorization里面，但getRequestToken方法是req.headers._headers.authorization，headers前面多了个_

**Comment by zmtlwzy** [comment]
经过msw处理过的请求参数确实是这样的
``` javascript
//  /mock/sys/user.ts
rest.get('/basic-api/getUserInfo', (req, res, ctx) => {
    console.log(req, 'req')
    const token = getRequestToken(req); // 确保getRequestToken的参数是rest的回调函数的第一个参数给的
})
```
![](https://user-images.githubusercontent.com/49909526/164885405-bb470a86-0894-4739-b250-1203c28bb8d0.png)

**Comment by MYxu** [comment]
npm run dev后通过**localhost**、**域名**访问打印出来的req是不同的
![image](https://user-images.githubusercontent.com/18640435/170279083-b1bbd2ed-d362-478b-be2e-1254f3cdf4b8.png)
![image](https://user-images.githubusercontent.com/18640435/170279750-dfd11ef9-ae51-49db-b00c-44c6fd292987.png)
